# Generated by Django 5.0.4 on 2024-04-15 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research_facilities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('price', models.IntegerField(default=1)),
                ('research_facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='research_facilities.researchfacility')),
            ],
        ),
    ]
